language: ruby
rvm:
  - 1.9.3
  - 2.0.0
matrix:
  exclude:
    - rvm: 2.0.0
branches:
  only:
    - spec
before_script:
  - bundle exec berks install --path vendor/cookbooks
script:
  - bundle exec "strainer test --except kitchen"